import 'package:flutter/material.dart';
import 'package:flutter_rating_bar/flutter_rating_bar.dart';
import 'package:flutter_svg/svg.dart';
import 'package:get/get.dart';
import 'package:subtap/controller/navigation_controller.dart';
import 'package:subtap/core/config/config.dart';
import 'package:subtap/core/shared_widgets/custom_button.dart';
import 'package:subtap/core/shared_widgets/custom_circular_avatar.dart';
import 'package:subtap/core/shared_widgets/custom_text.dart';
import 'package:subtap/core/shared_widgets/subtap_scaffold.dart';
import 'package:subtap/core/theme/app_color.dart';
import 'package:subtap/core/theme/assets.dart';
import 'package:subtap/core/theme/constane.dart';

part 'fav_subcontractor_appbar.dart';
part 'fav_subcontractor_card.dart';
part 'fav_subcontractor_profile.dart';
part 'fav_subcontractor_profile_appbar.dart';
part 'favorities_subcontractor_appbar.dart';
